### ISSUE TITLE
Missing dependency (for tests at least): PIL

### ISSUE THREAD

**Issue by vmichals** [HoME-Platform/home-platform#2]
```
ERROR: testGetColorsFromObjectBasic (tests.multimodalmaze.test_semantic.TestMaterialColorTable)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vince/workspace/home-platform/tests/multimodalmaze/test_semantic.py", line 50, in testGetColorsFromObjectBasic
    colorDescriptions = MaterialColorTable.getColorsFromObject(obj, mode='basic')
  File "/home/vince/workspace/home-platform/home_platform/semantic.py", line 86, in getColorsFromObject
    areas, colors, transparencies, _ = getColorAttributesFromModel(nodePath)
  File "/home/vince/workspace/home-platform/home_platform/rendering.py", line 546, in getColorAttributesFromModel
    img = scipy.ndimage.imread(texFilename)
  File "/home/vince/anaconda2/envs/home_platform/lib/python2.7/site-packages/scipy/ndimage/io.py", line 25, in imread
    raise ImportError("Could not import the Python Imaging Library (PIL)"
ImportError: Could not import the Python Imaging Library (PIL) required to load image files.  Please refer to http://pillow.readthedocs.org/en/latest/installation.html for installation instructions.
```

This can be fixed by:
```pip2 install Pillow```

**Comment by ankeshanand** [comment]
Thanks for the PR @vmichals!
