### ISSUE TITLE
problem with 'acoustics' engine in 'benchmarkGPU.py'

### ISSUE THREAD

**Issue by XuandongZhao** [HoME-Platform/home-platform#27]
I want to test the environment, and run benchmarkGPU.py in 'tests/benchmarks' folder. But I got the error as follow:

Traceback (most recent call last):
  File "/home/admin/work/home-platform/tests/benchmarks/benchmarkGPU.py", line 108, in <module>
    sys.exit(main())
  File "/home/admin/work/home-platform/tests/benchmarks/benchmarkGPU.py", line 100, in main
    print('FPS (all): ', getFpsAll(nbSteps))
  File "/home/admin/work/home-platform/tests/benchmarks/benchmarkGPU.py", line 46, in getFpsAll
    env.simulate(nbSteps=nbSteps)
  File "/home/admin/work/home-platform/tests/benchmarks/benchmark.py", line 97, in simulate
    self.step()
  File "/home/admin/work/home-platform/tests/benchmarks/benchmark.py", line 64, in step
    self.worlds[engine].step(dt=self.delta_time)
KeyError: 'acoustics'

Does anyone has the same problem? How can I fix it and use acoustics environment?

**Comment by Joll123** [comment]
你解决这个问题了吗
